---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  # CoreDNS config - fixes OCI link-local DNS timeout
  - ./coredns-config.yaml

  # Optional - uncomment when needed
  # - ./metrics-server.yaml
  # - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.1.3/deployments/multus-daemonset-thick.yml
# patches:
#   - path: ./multus-patch.yaml
