---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-issuers.yaml
  - ./certificates.yaml
  - ./flux-receiver.yaml
  - ./image-cache.yaml
  - ./image-updates.yaml
  - ./runtimeclass-kata.yaml
  - ./runtimeclass-gvisor.yaml
  - ./multus-network-attachment-definition.yaml
  - ./claude-system.yaml
  - ./cilium-l2-policy.yaml
  - ./gateway.yaml
